spring:
  application:
    name: SEWorld_backend
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/SEWorld}
    username: ${SPRING_DATASOURCE_USERNAME:simo_macca}
    password: ${SPRING_DATASOURCE_PASSWORD:Macauth.real}
  sql:
    init:
      mode: always
      platform: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      client:
        registration:
          # switch-edu-id
          switch-edu-id:
            client-id: test-client
            authorization-grant-type: authorization_code
            scope: openid
          # Google
          google:
            client-id: 8140374340-7snisghd72pnjfu0sffqkj1ria4do2pj.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
          # GitHub
          github:
            client-id: Ov23litwWoHghQl5qzRE
            client-secret: 2362e51bd463a4dc61c0fa101a2450de860da106
            scope: read:user, user:email
        provider:
          switch-edu-id:
            issuer-uri: https://auth.dev.si.usi.ch/auth/realms/simurbs
      resourceserver:
        jwt:
          issuer-uri: https://auth.dev.si.usi.ch/auth/realms/simurbs
  ai:
    ollama:
      embedding:
        model: deepseek-llm
      chat:
        options:
          model: deepseek-llm
          temperature: 0.3

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  error:
    include-stacktrace: never

app:
  frontend-url: "http://localhost:3000"
  instructors:
    - "johndoe@university.edu"
    - "janesmith@university.edu"
    - "instructor@example.com"